-- Run with CockroachDB's SQL client using an administrative migration account:
-- cockroach sql --url '<admin URL selecting database payment>' --set=errexit=true \
--   --file=Migrations/20260810161344_PaymentConfirmationOutbox.cockroach.sql
-- DDL is deliberately not wrapped in a transaction. The history row is last.

SELECT current_database() AS migration_database, current_user AS migration_user;

SELECT 1 / CASE WHEN current_database() = 'payment' THEN 1 ELSE 0 END
    AS correct_database;

SELECT 1 / CASE WHEN count(*) = 1 THEN 1 ELSE 0 END
    AS sky_payments_user_exists
FROM [SHOW USERS]
WHERE username = 'sky_payments';

SELECT 1 / CASE WHEN count(*) = 1 THEN 1 ELSE 0 END
    AS predecessor_applied
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20260728180315_CoflCoinServiceDeclarations';

SELECT 1 / CASE WHEN count(*) = 0 THEN 1 ELSE 0 END
    AS migration_unapplied
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20260810161344_PaymentConfirmationOutbox';

SELECT 1 / CASE WHEN count(*) = 0 THEN 1 ELSE 0 END
    AS target_table_absent
FROM information_schema.tables
WHERE table_catalog = current_database()
  AND table_schema = 'public'
  AND table_name = 'PaymentConfirmationOutbox';

CREATE TABLE public."PaymentConfirmationOutbox" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Provider" character varying(64) NOT NULL,
    "ProviderTransactionId" character varying(256) NOT NULL,
    "ConfirmationType" character varying(32) NOT NULL,
    "Payload" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PublishedAt" timestamp with time zone,
    "NextAttemptAt" timestamp with time zone NOT NULL,
    "Attempts" integer NOT NULL,
    "LeaseId" uuid,
    "LeaseUntil" timestamp with time zone,
    "LastError" character varying(2000),
    CONSTRAINT "PK_PaymentConfirmationOutbox" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "UX_PaymentConfirmationOutbox_Identity"
ON public."PaymentConfirmationOutbox"
    ("Provider", "ProviderTransactionId", "ConfirmationType");

CREATE INDEX "IX_PaymentConfirmationOutbox_Pending"
ON public."PaymentConfirmationOutbox" ("PublishedAt", "NextAttemptAt");

GRANT CONNECT ON DATABASE payment TO sky_payments;
GRANT USAGE ON SCHEMA public TO sky_payments;
GRANT SELECT, INSERT, UPDATE
ON TABLE public."PaymentConfirmationOutbox"
TO sky_payments;
GRANT USAGE
ON SEQUENCE public."PaymentConfirmationOutbox_Id_seq"
TO sky_payments;

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260810161344_PaymentConfirmationOutbox', '10.0.7');

SELECT "MigrationId", "ProductVersion"
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20260810161344_PaymentConfirmationOutbox';

SHOW CREATE TABLE public."PaymentConfirmationOutbox";
SHOW INDEXES FROM public."PaymentConfirmationOutbox";
SHOW GRANTS ON TABLE public."PaymentConfirmationOutbox" FOR sky_payments;
SHOW GRANTS FOR sky_payments;
