-- Run with cockroach sql --database=sky_payments --set=errexit=true --file=<this file>
-- and a task-scoped migration credential. payment is the Kubernetes namespace.
\set errexit true
-- DDL is not wrapped in a transaction; the migration history row is written last.
SELECT current_database() AS migration_database;
SELECT 1 / CASE WHEN current_database() = 'sky_payments' THEN 1 ELSE 0 END AS correct_database;
SELECT 1 / CASE WHEN count(*) = 1 THEN 1 ELSE 0 END AS predecessor_applied
FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260830092401_ExpertConfigOrderEvidence';

ALTER TABLE "Product" ADD "SlotCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "Product" ADD "SlotTier" character varying(32);

CREATE TABLE "TierSlots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Tier" character varying(32) NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    "AssignedUserId" character varying(32),
    "MinecraftUuid" character varying(32),
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_TierSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TierSlots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TierSlotGrants" (
    "TierSlotId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "Seconds" bigint NOT NULL,
    CONSTRAINT "PK_TierSlotGrants" PRIMARY KEY ("TransactionId", "TierSlotId"),
    CONSTRAINT "FK_TierSlotGrants_FiniteTransactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "FiniteTransactions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TierSlotGrants_TierSlots_TierSlotId" FOREIGN KEY ("TierSlotId") REFERENCES "TierSlots" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TierSlotGrants_TierSlotId" ON "TierSlotGrants" ("TierSlotId");

CREATE INDEX "IX_TierSlots_AssignedUserId_MinecraftUuid_Expires" ON "TierSlots" ("AssignedUserId", "MinecraftUuid", "Expires");

CREATE INDEX "IX_TierSlots_MinecraftUuid_Expires" ON "TierSlots" ("MinecraftUuid", "Expires");

CREATE INDEX "IX_TierSlots_UserId" ON "TierSlots" ("UserId");

GRANT SELECT, INSERT, UPDATE ON TABLE "TierSlots" TO sky_payments;
GRANT SELECT, INSERT ON TABLE "TierSlotGrants" TO sky_payments;
GRANT USAGE ON SEQUENCE "TierSlots_Id_seq" TO sky_payments;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260907153456_OwnerManagedTierSlots', '10.0.7');
