using System;
using System.ComponentModel.DataAnnotations;

namespace Coflnet.Payments.Models
{
    /// <summary>
    /// Tracks revenue generated by creator codes for payout calculation
    /// </summary>
    public class CreatorCodeRevenue
    {
        /// <summary>
        /// The unique identifier for this revenue record
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// The creator code ID that was used
        /// </summary>
        public int CreatorCodeId { get; set; }

        /// <summary>
        /// The creator code that was used
        /// </summary>
        public CreatorCode CreatorCode { get; set; }

        /// <summary>
        /// The user who made the purchase
        /// </summary>
        [Required]
        [MaxLength(32)]
        public string UserId { get; set; }

        /// <summary>
        /// The product ID that was purchased
        /// </summary>
        public int ProductId { get; set; }

        /// <summary>
        /// The original price before discount
        /// </summary>
        public decimal OriginalPrice { get; set; }

        /// <summary>
        /// The discount amount applied
        /// </summary>
        public decimal DiscountAmount { get; set; }

        /// <summary>
        /// The final price paid by the user
        /// </summary>
        public decimal FinalPrice { get; set; }

        /// <summary>
        /// The revenue share amount for the creator
        /// </summary>
        public decimal CreatorRevenue { get; set; }

        /// <summary>
        /// Currency code (ISO 4217)
        /// </summary>
        [Required]
        [MaxLength(3)]
        public string Currency { get; set; }

        /// <summary>
        /// The payment provider transaction ID for reference
        /// </summary>
        [MaxLength(255)]
        public string TransactionReference { get; set; }

        /// <summary>
        /// When this purchase was made
        /// </summary>
        public DateTime PurchasedAt { get; set; }

        /// <summary>
        /// Whether this revenue has been paid out to the creator
        /// </summary>
        public bool IsPaidOut { get; set; }

        /// <summary>
        /// When this revenue was paid out (if applicable)
        /// </summary>
        public DateTime? PaidOutAt { get; set; }
    }
}
